# Generated by Django 3.1.5 on 2021-02-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210202_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/img/no-image-found.png', null=True, upload_to=''),
        ),
    ]
