# Generated by Django 3.1.5 on 2021-02-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
