# Generated by Django 3.1.5 on 2021-02-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210215_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статусы заказа'},
        ),
        migrations.AddField(
            model_name='status',
            name='value',
            field=models.SlugField(max_length=20, null=True, verbose_name='Value'),
        ),
    ]
