# Generated by Django 3.1.5 on 2021-02-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210215_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='value',
            field=models.SlugField(blank=True, max_length=20, null=True, unique=True, verbose_name='Value'),
        ),
    ]
