# Generated by Django 3.1.5 on 2021-02-15 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210215_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='value',
            field=models.SlugField(blank=True, max_length=20, null=True, verbose_name='Value'),
        ),
    ]
